--SQLQuery0-CREATE DATABASE.sql
--CREATE DATABASE SPU_411_DDL
--ON
--(
--NAME       = SPU_411_DDL,
--FILENAME   = 'D:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SPU_411_DDL.mdf',
--SIZE       = 8 MB,
--MAXSIZE    = 500 MB,
--FILEGROWTH = 8 MB
--)
--LOG ON 
--(
--NAME       = SPU_411_Log,
--FILENAME   = 'D:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SPU_411_DDL.ldf',
--SIZE       = 8 MB,
--MAXSIZE    = 500 MB,
--FILEGROWTH = 5 MB
--)


CREATE DATABASE SPU_411_ALL
ON
(
NAME = SPU_411_ALL,
FILENAME =  'D:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SPU_411_ALL.mdf',
SIZE       = 8 MB,
MAXSIZE    = 500 MB,
FILEGROWTH = 8 MB
)
LOG ON 
(
NAME       = SPU_411_ALL_Log,
FILENAME   = 'D:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SPU_411_ALL.ldf',
SIZE       = 8 MB,
MAXSIZE    = 500 MB,
FILEGROWTH = 5 MB
)